language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anooppius/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anooppius/react-test npm test

after_success:
  - docker build -t anooppius/multi-container-demo-client ./client
  - docker build -t anooppius/multi-container-demo-nginx ./nginx
  - docker build -t anooppius/multi-container-demo-server ./server
  - docker build -t anooppius/multi-container-demo-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push anooppius/multi-container-demo-client
  - docker push anooppius/multi-container-demo-nginx
  - docker push anooppius/multi-container-demo-server
  - docker push anooppius/multi-container-demo-worker

deploy:
  provider: "elasticbeanstalk"
  region: "us-east-1"
  app: "multi-container"
  env: "Multicontainer-env"
  bucket_name: "elasticbeanstalk-us-east-1-730471093388"
  bucket_path: "multi-container"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
